In [19]:
import os
import pandas as pd


##extract the data
#read the casv file
df = pd.read_csv('pancreatic_cancer_prediction_sample.csv', nrows=10000)
print("Preview of the first dataset")
display(df.head())


#transform the data

df = df.drop_duplicates()
#Filter for cancer patients under age 40
result = df[df['Age'] < 40]
# Display result
display(result)


count_under40 = len(result)
print(f"Total number of cancer patients under 40: {count_under40}")

total_patients = df.shape[0]
print(f"Total number of cancer patients: {total_patients}")

result1 = df[df['Obesity'] == 1]

sum = len(result1)
print(f" Number  of patients who were obese: {sum}")

pertage = ((sum/total_patients)* 100)
print(f" Percentage of people who were obese: {pertage} % ")

df.to_csv('cleaned_data_pancreatic_cancer_prediction.csv', index=False)

Preview of the first dataset

,Country,Age,Gender,Smoking_History,Obesity,Diabetes,Chronic_Pancreatitis,Family_History,Hereditary_Condition,Jaundice,...,Stage_at_Diagnosis,Survival_Time_Months,Treatment_Type,Survival_Status,Alcohol_Consumption,Physical_Activity_Level,Diet_Processed_Food,Access_to_Healthcare,Urban_vs_Rural,Economic_Status
0,Canada,64,Female,0,0,0,0,0,0,0,...,Stage III,13,Surgery,0,0,Medium,Low,High,Urban,Low
1,South Africa,77,Male,1,1,0,0,0,0,0,...,Stage III,13,Chemotherapy,0,1,Medium,Medium,Medium,Urban,Low
2,India,71,Female,0,0,0,0,0,0,0,...,Stage IV,3,Chemotherapy,1,0,Medium,High,Low,Rural,Middle
3,Germany,56,Male,0,0,0,0,1,0,1,...,Stage IV,6,Radiation,0,1,Low,Low,Medium,Rural,Middle
4,United States,82,Female,0,0,0,0,1,0,0,...,Stage IV,9,Chemotherapy,1,0,Low,Medium,Medium,Rural,Low

,Country,Age,Gender,Smoking_History,Obesity,Diabetes,Chronic_Pancreatitis,Family_History,Hereditary_Condition,Jaundice,...,Stage_at_Diagnosis,Survival_Time_Months,Treatment_Type,Survival_Status,Alcohol_Consumption,Physical_Activity_Level,Diet_Processed_Food,Access_to_Healthcare,Urban_vs_Rural,Economic_Status
86,India,38,Male,1,1,0,0,0,0,0,...,Stage IV,9,Radiation,0,0,Medium,Low,High,Urban,Low
201,United States,36,Female,1,1,0,0,0,0,0,...,Stage IV,9,Chemotherapy,0,0,Low,Medium,High,Urban,High
219,China,38,Male,1,1,0,0,0,0,0,...,Stage II,8,Radiation,0,0,Medium,Low,Medium,Urban,Low
229,India,35,Female,1,0,0,1,0,0,0,...,Stage I,31,Radiation,0,0,Medium,Low,Medium,Urban,Low
318,United States,30,Male,0,0,0,0,0,0,0,...,Stage III,13,Chemotherapy,0,1,Medium,High,Medium,Rural,Middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9754,United States,32,Female,0,1,0,0,0,0,0,...,Stage III,18,Chemotherapy,0,0,Low,Low,Medium,Urban,Low
9782,India,34,Male,1,0,0,0,0,0,0,...,Stage IV,1,Chemotherapy,0,1,Low,Medium,Medium,Urban,Middle
9874,Germany,37,Male,1,1,0,0,0,0,0,...,Stage II,30,Radiation,0,0,Medium,High,Medium,Rural,Middle
9960,Germany,39,Female,0,1,0,0,0,1,0,...,Stage IV,8,Chemotherapy,0,0,Medium,High,Low,Urban,High
9975,United States,34,Male,0,0,1,0,0,0,0,...,Stage IV,6,Radiation,0,0,Medium,High,Medium,Urban,Middle

Total number of cancer patients under 40: 71
Total number of cancenr patients: 10000
 Number  of patients who were obese: 2481
 Percentage of people who were obese: 24.81 %

In [29]:
import pandas as pd
import sqlite3


df = pd.read_csv('pancreatic_cancer_prediction_sample.csv', nrows=10000)
display(df.head())
df.info()

#Transform the data
#dropping duplicates 
df = df.drop_duplicates()

#fill missing values with mean
df.fillna(df.mean(numeric_only = True), inplace = True)

#fill missing categorical values with "unknown"
df.fillna("Unknown", inplace = True)

display(df.head())
print("Let's check if there are any missing values.....")
print(df.isnull().sum())

#Load the data

conn = sqlite3.connect('pancreatic_cancer_clean.db')
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS pancreatic_cancer_clean(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Age INTEGER,
    Gender TEXT,
    SMOKING_HISTORY INTEGER,
    OBESITY INTEGER,
    DIABETES INTEGER,
    Chronic_Pancreatitis INTEGER,
    Family_History INTEGER,
    Hereditary_Condition INTEGER,
    Back_Pain INTEGER,
    Jaundice INTEGER,
    Abdominal_Discomfort  INTEGER,
    Weight_Loss   INTEGER,  
    Development_of_Type2_Diabetes  INTEGER, 
    Stage_at_Diagnosis TEXT,
    Survival_Time_Months INTEGER,  
    Treatment_Type TEXT,
    Survival_Status INTEGER,
    Alcohol_Consumption INTEGER,
    Physical_Activity_Level INTEGER,
    Diet_Processed_Food TEXT,
    Access_to_Healthcare TEXT,
    Urban_vs_Rural TEXT,
    Economic_Status TEXT  
);
""")
conn.commit()

#Insert cleaned  data into SQL Lite
df.to_sql('pancreatic_cancer_clean', conn, if_exists='replace', index=False)

#query to validate the pipeline
query = "select  * from pancreatic_cancer_clean order by age desc limit 5;"
result = pd.read_sql(query, conn)
display(result)

#close connection
conn.close()

,Country,Age,Gender,Smoking_History,Obesity,Diabetes,Chronic_Pancreatitis,Family_History,Hereditary_Condition,Jaundice,...,Stage_at_Diagnosis,Survival_Time_Months,Treatment_Type,Survival_Status,Alcohol_Consumption,Physical_Activity_Level,Diet_Processed_Food,Access_to_Healthcare,Urban_vs_Rural,Economic_Status
0,Canada,64,Female,0,0,0,0,0,0,0,...,Stage III,13,Surgery,0,0,Medium,Low,High,Urban,Low
1,South Africa,77,Male,1,1,0,0,0,0,0,...,Stage III,13,Chemotherapy,0,1,Medium,Medium,Medium,Urban,Low
2,India,71,Female,0,0,0,0,0,0,0,...,Stage IV,3,Chemotherapy,1,0,Medium,High,Low,Rural,Middle
3,Germany,56,Male,0,0,0,0,1,0,1,...,Stage IV,6,Radiation,0,1,Low,Low,Medium,Rural,Middle
4,United States,82,Female,0,0,0,0,1,0,0,...,Stage IV,9,Chemotherapy,1,0,Low,Medium,Medium,Rural,Low

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        10000 non-null  object
 1   Age                            10000 non-null  int64
 2   Gender                         10000 non-null  object
 3   Smoking_History                10000 non-null  int64
 4   Obesity                        10000 non-null  int64
 5   Diabetes                       10000 non-null  int64
 6   Chronic_Pancreatitis           10000 non-null  int64
 7   Family_History                 10000 non-null  int64
 8   Hereditary_Condition           10000 non-null  int64
 9   Jaundice                       10000 non-null  int64
 10  Abdominal_Discomfort           10000 non-null  int64
 11  Back_Pain                      10000 non-null  int64
 12  Weight_Loss                    10000 non-null  int64
 13  Development_of_Type2_Diabetes  10000 non-null  int64
 14  Stage_at_Diagnosis             10000 non-null  object
 15  Survival_Time_Months           10000 non-null  int64
 16  Treatment_Type                 10000 non-null  object
 17  Survival_Status                10000 non-null  int64
 18  Alcohol_Consumption            10000 non-null  int64
 19  Physical_Activity_Level        10000 non-null  object
 20  Diet_Processed_Food            10000 non-null  object
 21  Access_to_Healthcare           10000 non-null  object
 22  Urban_vs_Rural                 10000 non-null  object
 23  Economic_Status                10000 non-null  object
dtypes: int64(15), object(9)
memory usage: 1.8+ MB

,Country,Age,Gender,Smoking_History,Obesity,Diabetes,Chronic_Pancreatitis,Family_History,Hereditary_Condition,Jaundice,...,Stage_at_Diagnosis,Survival_Time_Months,Treatment_Type,Survival_Status,Alcohol_Consumption,Physical_Activity_Level,Diet_Processed_Food,Access_to_Healthcare,Urban_vs_Rural,Economic_Status
0,Canada,64,Female,0,0,0,0,0,0,0,...,Stage III,13,Surgery,0,0,Medium,Low,High,Urban,Low
1,South Africa,77,Male,1,1,0,0,0,0,0,...,Stage III,13,Chemotherapy,0,1,Medium,Medium,Medium,Urban,Low
2,India,71,Female,0,0,0,0,0,0,0,...,Stage IV,3,Chemotherapy,1,0,Medium,High,Low,Rural,Middle
3,Germany,56,Male,0,0,0,0,1,0,1,...,Stage IV,6,Radiation,0,1,Low,Low,Medium,Rural,Middle
4,United States,82,Female,0,0,0,0,1,0,0,...,Stage IV,9,Chemotherapy,1,0,Low,Medium,Medium,Rural,Low

Let's check if there are any missing values.....
Country                          0
Age                              0
Gender                           0
Smoking_History                  0
Obesity                          0
Diabetes                         0
Chronic_Pancreatitis             0
Family_History                   0
Hereditary_Condition             0
Jaundice                         0
Abdominal_Discomfort             0
Back_Pain                        0
Weight_Loss                      0
Development_of_Type2_Diabetes    0
Stage_at_Diagnosis               0
Survival_Time_Months             0
Treatment_Type                   0
Survival_Status                  0
Alcohol_Consumption              0
Physical_Activity_Level          0
Diet_Processed_Food              0
Access_to_Healthcare             0
Urban_vs_Rural                   0
Economic_Status                  0
dtype: int64

,Country,Age,Gender,Smoking_History,Obesity,Diabetes,Chronic_Pancreatitis,Family_History,Hereditary_Condition,Jaundice,...,Stage_at_Diagnosis,Survival_Time_Months,Treatment_Type,Survival_Status,Alcohol_Consumption,Physical_Activity_Level,Diet_Processed_Food,Access_to_Healthcare,Urban_vs_Rural,Economic_Status
0,United States,90,Male,1,0,0,0,1,0,1,...,Stage IV,7,Surgery,0,0,Medium,High,High,Urban,High
1,India,90,Male,0,0,0,0,0,0,0,...,Stage IV,5,Chemotherapy,0,1,Medium,High,High,Urban,Middle
2,Germany,90,Female,0,0,0,0,0,0,0,...,Stage IV,10,Surgery,0,0,Low,Medium,Medium,Urban,Low
3,United Kingdom,90,Male,0,0,0,0,0,0,0,...,Stage II,31,Chemotherapy,1,0,Medium,Medium,Medium,Urban,Middle
4,South Africa,90,Female,0,1,0,0,0,0,0,...,Stage IV,7,Surgery,0,0,Medium,Medium,Medium,Urban,Middle